# Generated by Django 5.2 on 2025-04-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(choices=[('U', 'Unassigned'), ('A', 'Active'), ('C', 'Closed'), ('P', 'Paused'), ('R', 'Review pending')], default='U', max_length=1),
        ),
    ]
