# Generated by Django 5.2 on 2025-04-22 23:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_alter_taskhistory_date_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskNotes',
            new_name='TaskNote',
        ),
    ]
