# Generated by Django 5.2 on 2025-04-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_rename_tasknotes_tasknote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasknote',
            old_name='user',
            new_name='created_by',
        ),
    ]
